### PR TITLE
Fix `getEgoVehicleId` in Linux

### LINKED ISSUE #108: `getEgoVehicleId` does not compile in Linux
It looks like there's an issue with the definition of the ego vehicle name grabber function introduced in PR #100

```
[ 10%] Building CXX object monodrive/core/CMakeFiles/monodrive.dir/src/Simulator.cpp.o
/home/bradnull/projects/monodrive-client/monodrive/core/src/Simulator.cpp: In member function ‘std::__cxx11::string Simulator::getEgoVehicleId()’:
/home/bradnull/projects/monodrive-client/monodrive/core/src/Simulator.cpp:385:2: error: cannot bind non-const lvalue reference of type ‘Simulator::getEgoVehicleId()::<lambda(nlohmann::json&)>&’ to an rvalue of type ‘Simulator::getEgoVehicleId()::<lambda(nlohmann::json&)>’
  };
  ^
```

### PR DESCRIPTION
**Pull request by bradleynull**
## Overview

This fixes a build issue with gcc version 7.5 that was introduced in #100 and reported in #108.

## Changes

Fixed the build issue by making the function `const`

## Testing

Ensure the client code builds on gcc 7.5+ and Windows.

Run the  lights example to see that the function works correctly.

Closes #108

### CODE REVIEW

**Review by stephendb — APPROVED** [review]
This is fine to fix the build issue. However, need to create an issue, this is the wrong pattern for ID. SHOULD NOT look at the state ID to figure out which actor we are controlling. This is set by the Scenario file and the names are not guaranteed to be the same, only guaranteed to CONTAIN the same name name.
Scenario File: vehicle_01
State ID: vehicle_01_43143214321
