### ISSUE TITLE
`getEgoVehicleId` does not compile in Linux

### ISSUE THREAD

**Issue by bradleynull** [monoDriveIO/monodrive-client#108]
It looks like there's an issue with the definition of the ego vehicle name grabber function introduced in PR #100

```
[ 10%] Building CXX object monodrive/core/CMakeFiles/monodrive.dir/src/Simulator.cpp.o
/home/bradnull/projects/monodrive-client/monodrive/core/src/Simulator.cpp: In member function ‘std::__cxx11::string Simulator::getEgoVehicleId()’:
/home/bradnull/projects/monodrive-client/monodrive/core/src/Simulator.cpp:385:2: error: cannot bind non-const lvalue reference of type ‘Simulator::getEgoVehicleId()::<lambda(nlohmann::json&)>&’ to an rvalue of type ‘Simulator::getEgoVehicleId()::<lambda(nlohmann::json&)>’
  };
  ^
```

**Comment by bradleynull** [comment]
Closed by PR #109
